/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("mysql:mysql-connector-java:8.0.33")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.eruditus.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

val jdbcUrl: String = project.findProperty("jdbc.url") as String
val jdbcUser: String = project.findProperty("jdbc.user") as String
val jdbcPassword: String = project.findProperty("jdbc.password") as String

tasks.withType<JavaExec> {
    systemProperty("jdbc.url", jdbcUrl)
    systemProperty("jdbc.user", jdbcUser)
    systemProperty("jdbc.password", jdbcPassword)
}
